projects = { "/Users/tom/personal/heyo" = { trust_level = "trusted" }, "/Users/tom/personal/heyo-bun" = { trust_level = "trusted" }, "/Users/tom/personal/wino" = { trust_level = "trusted" } }
approval_policy = "never"
sandbox_mode = "danger-full-access"
model = "gpt-5-codex"
model_reasoning_effort = "high"

[sandbox_workspace_write]
network_access = true

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true

[features]
web_search_request = true
view_image_tool = true
